# Generated by Django 5.0.6 on 2024-06-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("susgpt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="output",
            field=models.TextField(blank=True, null=True),
        ),
    ]
